---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: download
spec:
  hosts:
  - nginx.demo-services.svc.cluster.local
  http:
  - route:
    - destination:
        host: nginx.demo-services.svc.cluster.local
        subset: downloadv1